[options]
library = "GTop"
version = "2.0"
target_path = "."
min_cfg_version = "2.0"
work_mode = "sys"
girs_directories = ["../gir-files/"]


external_libraries = [
   "GLib",
   "GObject",
   "Gio",
]